import type { Pos, Specimen, TrailItem } from "./types";
import { posLabel, tempPos } from "./logic";

function makeSpec(
  partial: Partial<Specimen> & Pick<Specimen, "id" | "speciesCode" | "speciesName" | "collector">,
  at?: string,
): Specimen {
  const pos: Pos = partial.pos ?? tempPos(partial.id);
  const atTime = at ?? (partial.reviewDate ? `${partial.reviewDate}T09:00` : "2026-09-18T09:30");
  const base: Specimen = {
    id: partial.id,
    speciesCode: partial.speciesCode,
    speciesName: partial.speciesName,
    latinName: partial.latinName ?? "",
    collector: partial.collector,
    elevation: partial.elevation ?? null,
    location: partial.location ?? "",
    habitat: partial.habitat ?? "",
    pressStatus: partial.pressStatus ?? "已压制",
    status: partial.status ?? "待鉴定",
    pos,
    reviewer: partial.reviewer,
    reviewDate: partial.reviewDate,
    basis: partial.basis,
    trail: [],
  };
  const trail: TrailItem[] = [
    {
      at: atTime,
      from: "—",
      to: posLabel(pos),
      note: "入库登记",
      kind: "in",
    },
  ];
  return { ...base, trail };
}

// 已入柜标本：A-01(4位满)、B-02(4位满)、A-02(5位满，演示满位暂停)
const shelved: Specimen[] = [
  makeSpec({
    id: "HX-240501-02",
    speciesCode: "AC001",
    speciesName: "色木槭",
    latinName: "Acer pictum",
    collector: "李恒",
    elevation: 1500,
    location: "峨眉山清音阁",
    habitat: "阔叶林下",
    status: "已入库",
    pos: { cabinet: "A", layer: "01", slot: "01" },
    reviewer: "王鉴定",
    reviewDate: "2026-09-02",
    basis: "形态与馆藏标本一致",
  }),
  makeSpec({
    id: "HX-240501-03",
    speciesCode: "AC001",
    speciesName: "色木槭",
    latinName: "Acer pictum",
    collector: "李恒",
    elevation: 1520,
    location: "峨眉山清音阁",
    habitat: "林缘",
    status: "已入库",
    pos: { cabinet: "A", layer: "01", slot: "02" },
    reviewer: "王鉴定",
    reviewDate: "2026-09-02",
  }),
  makeSpec({
    id: "HX-240502-01",
    speciesCode: "AC002",
    speciesName: "青榨槭",
    latinName: "Acer davidii",
    collector: "周云",
    elevation: 1200,
    location: "青城山天师洞",
    habitat: "沟谷林",
    status: "已入库",
    pos: { cabinet: "A", layer: "01", slot: "03" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-03",
  }),
  makeSpec({
    id: "HX-240502-02",
    speciesCode: "AC002",
    speciesName: "青榨槭",
    latinName: "Acer davidii",
    collector: "周云",
    elevation: 1230,
    location: "青城山天师洞",
    habitat: "溪边",
    status: "已入库",
    pos: { cabinet: "A", layer: "01", slot: "04" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-03",
  }),
  makeSpec({
    id: "HX-240410-05",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "赵芃",
    elevation: 900,
    location: "瓦屋山象尔岩",
    habitat: "阳坡灌丛",
    status: "已入库",
    pos: { cabinet: "A", layer: "02", slot: "01" },
    reviewer: "王鉴定",
    reviewDate: "2026-08-28",
  }),
  makeSpec({
    id: "HX-240410-06",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "赵芃",
    elevation: 910,
    location: "瓦屋山象尔岩",
    habitat: "阳坡",
    status: "已入库",
    pos: { cabinet: "A", layer: "02", slot: "02" },
    reviewer: "王鉴定",
    reviewDate: "2026-08-28",
  }),
  makeSpec({
    id: "HX-240411-01",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "孙铭",
    elevation: 880,
    location: "瓦屋山古福坪",
    habitat: "林缘荒坡",
    status: "已入库",
    pos: { cabinet: "A", layer: "02", slot: "03" },
    reviewer: "王鉴定",
    reviewDate: "2026-08-29",
  }),
  makeSpec({
    id: "HX-240411-02",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "孙铭",
    elevation: 870,
    location: "瓦屋山古福坪",
    habitat: "荒坡",
    status: "已入库",
    pos: { cabinet: "A", layer: "02", slot: "04" },
    reviewer: "王鉴定",
    reviewDate: "2026-08-29",
  }),
  makeSpec({
    id: "HX-240412-01",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "孙铭",
    elevation: 950,
    location: "瓦屋山双洞溪",
    habitat: "溪边坡地",
    status: "已入库",
    pos: { cabinet: "A", layer: "02", slot: "05" },
    reviewer: "陈蓉",
    reviewDate: "2026-08-30",
  }),
  makeSpec({
    id: "HX-240601-04",
    speciesCode: "HP001",
    speciesName: "金丝桃",
    latinName: "Hypericum monogynum",
    collector: "何岚",
    elevation: 600,
    location: "龙泉山观景台",
    habitat: "山坡灌丛",
    status: "已入库",
    pos: { cabinet: "B", layer: "02", slot: "01" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-05",
  }),
  makeSpec({
    id: "HX-240601-05",
    speciesCode: "HP001",
    speciesName: "金丝桃",
    latinName: "Hypericum monogynum",
    collector: "何岚",
    elevation: 610,
    location: "龙泉山观景台",
    habitat: "灌丛",
    status: "已入库",
    pos: { cabinet: "B", layer: "02", slot: "02" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-05",
  }),
  makeSpec({
    id: "HX-240602-01",
    speciesCode: "HP001",
    speciesName: "金丝桃",
    latinName: "Hypericum monogynum",
    collector: "吴桐",
    elevation: 580,
    location: "龙泉山周家湾",
    habitat: "路边",
    status: "已入库",
    pos: { cabinet: "B", layer: "02", slot: "03" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-05",
  }),
  makeSpec({
    id: "HX-240602-02",
    speciesCode: "HP001",
    speciesName: "金丝桃",
    latinName: "Hypericum monogynum",
    collector: "吴桐",
    elevation: 590,
    location: "龙泉山周家湾",
    habitat: "田埂边",
    status: "已入库",
    pos: { cabinet: "B", layer: "02", slot: "04" },
    reviewer: "陈蓉",
    reviewDate: "2026-09-05",
  }),
];

// 待鉴定：色木槭（采集人不同 + 海拔差>300，须依据）→ 目标 A-01 满层，暂停
const pending: Specimen[] = [
  makeSpec({
    id: "HX-240901-01",
    speciesCode: "AC001",
    speciesName: "色木槭",
    latinName: "Acer pictum",
    collector: "李恒",
    elevation: 1100,
    location: "峨眉山伏虎寺",
    habitat: "常绿阔叶林中",
    pressStatus: "已压制",
  }),
  makeSpec({
    id: "HX-240901-02",
    speciesCode: "AC001",
    speciesName: "色木槭",
    latinName: "Acer pictum",
    collector: "周云",
    elevation: 1450,
    location: "峨眉山清音阁",
    habitat: "林缘沟旁",
    pressStatus: "已压制",
  }),
  makeSpec({
    id: "HX-240902-01",
    speciesCode: "AC001",
    speciesName: "色木槭",
    latinName: "Acer pictum",
    collector: "郑凯",
    elevation: 1760,
    location: "峨眉山洗象池",
    habitat: "针阔混交林下",
    pressStatus: "待压制",
  }),
  // 露珠草：同采集人、海拔差小，无须依据；目标 C-01 有空位，可直接迁移
  makeSpec({
    id: "HX-240903-01",
    speciesCode: "CR001",
    speciesName: "露珠草",
    latinName: "Circaea cordata",
    collector: "何岚",
    elevation: 1300,
    location: "瓦屋山鸳鸯池",
    habitat: "阴湿林下",
  }),
  makeSpec({
    id: "HX-240903-02",
    speciesCode: "CR001",
    speciesName: "露珠草",
    latinName: "Circaea cordata",
    collector: "何岚",
    elevation: 1350,
    location: "瓦屋山鸳鸯池",
    habitat: "溪边腐殖土",
  }),
  // 蒲公英：海拔差 > 300，须依据；目标 B-01 有空位
  makeSpec({
    id: "HX-240904-01",
    speciesCode: "TG001",
    speciesName: "蒲公英",
    latinName: "Taraxacum mongolicum",
    collector: "赵芃",
    elevation: 450,
    location: "成都平原田埂",
    habitat: "田间路旁",
  }),
  makeSpec({
    id: "HX-240904-02",
    speciesCode: "TG001",
    speciesName: "蒲公英",
    latinName: "Taraxacum mongolicum",
    collector: "赵芃",
    elevation: 820,
    location: "龙泉山半山步道",
    habitat: "向阳草地",
  }),
  // 蕨菜单份：目标 A-02 满层，复核后演示满位暂停（本批无须依据）
  makeSpec({
    id: "HX-240905-01",
    speciesCode: "PT001",
    speciesName: "蕨菜",
    latinName: "Pteridium revolutum",
    collector: "孙铭",
    elevation: 920,
    location: "瓦屋山观瀑亭",
    habitat: "疏林荒坡",
  }),
];

export function seedSpecimens(): Specimen[] {
  return [...shelved.map((s) => ({ ...s, trail: s.trail.map((t) => ({ ...t })) })), ...pending];
}
